/**
 * Dual-layer value — scarcity without starving builders.
 *
 * LAYER A — PIX (scarce monetary / security asset)
 *   Hard cap 10,300,000,000 PIX, minted flat at 50 per pixel to a horizon of
 *   206,000,000 pixels, which reaches the ceiling exactly. Pays sequencers and
 *   secures the ledger.
 *   Subdivided into 1e8 base units (like sats), so the ceiling is not a UX
 *   bottleneck: 10.3e9 * 1e8 = 1.03e18 spendable units.
 *
 * LAYER B — Light Credits (uncapped developer / agent fuel)
 *   Metered for Lumen runs, MCP/agent tool calls, SISO message relays,
 *   optical ceremonies, and app compute. Regenerated by useful work and
 *   subnet capacity — never a hard global cap that blocks builders.
 *
 * Rule of thumb:
 *   PIX  = "gold" (hold, stake, bridge collateral, final settlement)
 *   Credits = "electricity" (build, agent, shine messages all day)
 */

/**
 * One PIX for every human alive at the peak of humanity.
 *
 * 21,000,000 was Satoshi's number and meant nothing here — a borrowed ceiling for
 * a ledger that is not money. This one says what the picture is for: population is
 * projected to peak near 10.3 billion around 2084 and decline after, so the cap is
 * the largest number of people who will ever be alive at once.
 *
 * It does not need to be an accurate census and cannot be — a chain cannot read
 * the world's population, which is why the peg in `presence-peg.ts` had to be
 * abandoned as a *rule*. As a ceiling it needs no oracle: it is a fixed number
 * chosen for a reason, and the reason is legible to anyone.
 *
 * The schedule reaches it exactly. See docs/EMISSION.md.
 *
 * Settled 16 August 2026. The file header above claimed 21,000,000 for five days
 * after the constant changed, which is how a reader ends up trusting a comment over
 * the code it sits on top of. `scripts/claims-guard-selftest.ts` now fails the build
 * if any file states a supply schedule this module does not implement.
 */
export const PIX_HARD_CAP = 10_300_000_000;
/** Base units per PIX — so the ceiling never limits micropayments or fees. */
export const PIX_BASE_UNITS = 100_000_000;
export const GENESIS_LIGHT_REWARD = 50;
/** Monetary fee in base units (0 = free during bootstrap). */
export const BASE_REVELATION_FEE_UNITS = 0;

/** Uncapped builder fuel — not scarce money. */
export const LIGHT_CREDITS_PER_ILLUMINATION = 10_000;
export const LIGHT_CREDIT_COSTS = {
  lumenCall: 10,
  mcpToolCall: 5,
  sisoShineOut: 25,
  sisoShineIn: 25,
  opticalProject: 2,
  rpcHeavyQuery: 1,
} as const;

export interface EmissionInfo {
  pixelIndex: number;
  rewardPix: number;
  rewardUnits: number;
  mintedPixToDate: number;
  remainingPix: number;
  hardCapPix: number;
  baseUnitsPerPix: number;
  totalBaseUnitsAtCap: number;
}

/**
 * Pixels that carry a reward: 206,000,000 x 50 PIX is exactly PIX_HARD_CAP.
 *
 * There used to be a halving here, inherited from Bitcoin without Bitcoin's base
 * unit — integer division truncated every era, so the series landed 630,000 short
 * of the ceiling it claimed. Bitcoin halves in satoshis and lands 0.0000001% under;
 * this halved in whole PIX and landed 3% under. Flat emission has no such gap and
 * reaches the ceiling exactly, which is why `PIX_SCHEDULE_TOTAL === PIX_HARD_CAP`
 * is an assertion rather than an aspiration.
 */
export const LIGHT_HORIZON = PIX_HARD_CAP / GENESIS_LIGHT_REWARD;

/**
 * A flat reward to a horizon, not a halving.
 *
 * Halving front-loads a subsidy to buy mining security. There is no mining here
 * and no hash race to subsidise, so the curve was paying for something that does
 * not exist. Flat makes "every moment is worth the same" true rather than
 * aspirational, and it reaches the cap exactly.
 *
 * Identical to the old schedule below pixel 210,000 — both pay 50 — so no chain
 * in existence is revalued by this.
 */
export function lightReward(pixelIndex: number): number {
  if (pixelIndex < 0 || pixelIndex >= LIGHT_HORIZON) return 0;
  return GENESIS_LIGHT_REWARD;
}

export function lightRewardUnits(pixelIndex: number): number {
  return lightReward(pixelIndex) * PIX_BASE_UNITS;
}

/**
 * Total minted through `pixelCount` pixels.
 *
 * Closed form over eras rather than a loop over pixels. This is called once per
 * block by `validateAndApplyBlockTxs` and `verifyChain`, so the old O(n) version
 * made validating an N-pixel chain cost N^2/2 iterations — 5x10^11 at a million
 * pixels. Values are identical to the loop; `test:scale` asserts that.
 */
export function mintedThrough(pixelCount: number): number {
  if (!Number.isFinite(pixelCount) || pixelCount <= 0) return 0;
  return Math.min(Math.floor(pixelCount), LIGHT_HORIZON) * GENESIS_LIGHT_REWARD;
}

/**
 * What the schedule mints, ever. Now equal to PIX_HARD_CAP rather than 3% under
 * it, so the declared ceiling is a fact instead of an aspiration.
 */
export const PIX_SCHEDULE_TOTAL = mintedThrough(LIGHT_HORIZON);

export function emissionInfo(nextPixelIndex: number): EmissionInfo {
  const mintedPixToDate = mintedThrough(nextPixelIndex);
  const rewardPix = lightReward(nextPixelIndex);
  return {
    pixelIndex: nextPixelIndex,
    rewardPix,
    rewardUnits: rewardPix * PIX_BASE_UNITS,
    mintedPixToDate,
    remainingPix: Math.max(0, PIX_HARD_CAP - mintedPixToDate),
    hardCapPix: PIX_HARD_CAP,
    baseUnitsPerPix: PIX_BASE_UNITS,
    totalBaseUnitsAtCap: PIX_HARD_CAP * PIX_BASE_UNITS,
  };
}

export function assertUnderCap(mintedToDate: number, newMint: number): void {
  if (mintedToDate + newMint > PIX_HARD_CAP) {
    throw new Error(`PIX hard cap exceeded (${mintedToDate + newMint} > ${PIX_HARD_CAP})`);
  }
}

/** Credit meter for a builder / agent identity (uncapped issuance side). */
export interface LightCreditAccount {
  id: string;
  credits: number;
}

export function grantIlluminationCredits(account: LightCreditAccount): LightCreditAccount {
  return {
    ...account,
    credits: account.credits + LIGHT_CREDITS_PER_ILLUMINATION,
  };
}

export function spendCredits(
  account: LightCreditAccount,
  cost: number,
  reason: string,
): LightCreditAccount {
  if (account.credits < cost) {
    throw new Error(
      `Insufficient Light Credits for ${reason} (have ${account.credits}, need ${cost})`,
    );
  }
  return { ...account, credits: account.credits - cost };
}

export function valueThesis(): {
  cap: number;
  baseUnits: number;
  dualLayer: string;
  analogy: string;
  issuance: string;
  sinks: string[];
  whyHold: string[];
  whyNotLimitDevs: string;
} {
  return {
    cap: PIX_HARD_CAP,
    baseUnits: PIX_BASE_UNITS,
    dualLayer: "PIX is scarce money/security; Light Credits are uncapped builder/agent fuel.",
    analogy:
      "A ceiling chosen for what the picture is for, not inherited from Bitcoin: one PIX for every human alive at the projected peak of humanity (~10.3 billion, around 2084). Flat emission of 50 PIX per pixel reaches it exactly. Credits are builder fuel. A ceiling is scarcity, not a valuation — never multiply it by a quote. See docs/EMISSION.md.",
    issuance:
      "New PIX only via light rewards when a sequencer illuminates a pixel (PoLS), flat at 50 per pixel. Day one = illuminate or shine in; no founder dump. Whether a per-pixel emission belongs in this design at all is an open question — PoLS has no expensive work to subsidise (docs/EMISSION.md).",
    sinks: [
      "Revelation fees paid to sequencers (anti-spam + security budget)",
      "Bridge collateral — PIX locked/escrowed for shineOut, then released",
    ],
    whyHold: [
      "Scarce settlement & bridge collateral",
      "Sequencer security budget",
      "Long-term monetary premium",
    ],
    whyNotLimitDevs:
      "Apps, agents, and SISO messages spend Light Credits (regenerated), never the PIX ceiling.",
  };
}
