/**
 * Dual-layer value — scarcity without starving builders.
 *
 * LAYER A — PIX (scarce monetary / security asset)
 *   Hard cap 21,000,000 PIX (Bitcoin-grade schedule).
 *   Pays sequencers, secures the ledger, collateralizes bridges.
 *   Subdivided into 1e8 base units (like sats) so 21M is NOT a UX bottleneck:
 *     21e6 * 1e8 = 2.1e15 spendable units.
 *
 * LAYER B — Light Credits (uncapped developer / agent fuel)
 *   Metered for Lumen runs, MCP/agent tool calls, SISO message relays,
 *   optical ceremonies, and app compute. Regenerated by useful work and
 *   subnet capacity — never a hard global cap that blocks builders.
 *
 * Rule of thumb:
 *   PIX  = "gold" (hold, stake, bridge collateral, final settlement)
 *   Credits = "electricity" (build, agent, shine messages all day)
 */

export const PIX_HARD_CAP = 21_000_000;
/** Base units per PIX — prevents 21M from limiting micropayments / fees. */
export const PIX_BASE_UNITS = 100_000_000;
export const LIGHT_ERA_LENGTH = 210_000;
export const GENESIS_LIGHT_REWARD = 50;
/** Monetary fee in base units (0 = free during bootstrap). */
export const BASE_REVELATION_FEE_UNITS = 0;

/** Uncapped builder fuel — not scarce money. */
export const LIGHT_CREDITS_PER_ILLUMINATION = 10_000;
export const LIGHT_CREDIT_COSTS = {
  lumenCall: 10,
  mcpToolCall: 5,
  sisoShineOut: 25,
  sisoShineIn: 25,
  opticalProject: 2,
  rpcHeavyQuery: 1,
} as const;

export interface EmissionInfo {
  pixelIndex: number;
  era: number;
  rewardPix: number;
  rewardUnits: number;
  mintedPixToDate: number;
  remainingPix: number;
  hardCapPix: number;
  baseUnitsPerPix: number;
  totalBaseUnitsAtCap: number;
}

export function lightReward(pixelIndex: number): number {
  if (pixelIndex < 0) return 0;
  const era = Math.floor(pixelIndex / LIGHT_ERA_LENGTH);
  if (era >= 64) return 0;
  return Math.floor(GENESIS_LIGHT_REWARD / Math.pow(2, era));
}

export function lightRewardUnits(pixelIndex: number): number {
  return lightReward(pixelIndex) * PIX_BASE_UNITS;
}

export function mintedThrough(pixelCount: number): number {
  let total = 0;
  for (let i = 0; i < pixelCount; i++) total += lightReward(i);
  return total;
}

export function emissionInfo(nextPixelIndex: number): EmissionInfo {
  const mintedPixToDate = mintedThrough(nextPixelIndex);
  const rewardPix = lightReward(nextPixelIndex);
  return {
    pixelIndex: nextPixelIndex,
    era: Math.floor(Math.max(0, nextPixelIndex) / LIGHT_ERA_LENGTH),
    rewardPix,
    rewardUnits: rewardPix * PIX_BASE_UNITS,
    mintedPixToDate,
    remainingPix: Math.max(0, PIX_HARD_CAP - mintedPixToDate),
    hardCapPix: PIX_HARD_CAP,
    baseUnitsPerPix: PIX_BASE_UNITS,
    totalBaseUnitsAtCap: PIX_HARD_CAP * PIX_BASE_UNITS,
  };
}

export function assertUnderCap(mintedToDate: number, newMint: number): void {
  if (mintedToDate + newMint > PIX_HARD_CAP) {
    throw new Error(`PIX hard cap exceeded (${mintedToDate + newMint} > ${PIX_HARD_CAP})`);
  }
}

/** Credit meter for a builder / agent identity (uncapped issuance side). */
export interface LightCreditAccount {
  id: string;
  credits: number;
}

export function grantIlluminationCredits(account: LightCreditAccount): LightCreditAccount {
  return {
    ...account,
    credits: account.credits + LIGHT_CREDITS_PER_ILLUMINATION,
  };
}

export function spendCredits(
  account: LightCreditAccount,
  cost: number,
  reason: string,
): LightCreditAccount {
  if (account.credits < cost) {
    throw new Error(
      `Insufficient Light Credits for ${reason} (have ${account.credits}, need ${cost})`,
    );
  }
  return { ...account, credits: account.credits - cost };
}

export function valueThesis(): {
  cap: number;
  baseUnits: number;
  dualLayer: string;
  analogy: string;
  issuance: string;
  sinks: string[];
  whyHold: string[];
  whyNotLimitDevs: string;
} {
  return {
    cap: PIX_HARD_CAP,
    baseUnits: PIX_BASE_UNITS,
    dualLayer: "PIX is scarce money/security; Light Credits are uncapped builder/agent fuel.",
    analogy:
      "Same 21M hard-cap math as Bitcoin for PIX; 1 PIX = 1e8 units so micropayments never starve. Credits are ICP-style cycles for compute/SISO/MCP.",
    issuance: "New PIX only via light rewards when a sequencer illuminates a pixel (PoLS).",
    sinks: [
      "Revelation fees paid to sequencers (anti-spam + security budget)",
      "Bridge collateral — PIX locked/escrowed for shineOut, then released",
    ],
    whyHold: [
      "Scarce settlement & bridge collateral",
      "Sequencer security budget",
      "Long-term monetary premium",
    ],
    whyNotLimitDevs:
      "Apps, agents, and SISO messages spend Light Credits (regenerated), not the 21M PIX cap.",
  };
}
