/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ShineRouteImport } from './routes/shine'
import { Route as McflamingoRouteImport } from './routes/mcflamingo'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DoorsRouteImport } from './routes/doors'
import { Route as ContinuityRouteImport } from './routes/continuity'
import { Route as BillboardRouteImport } from './routes/billboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContinuityJoinTokenRouteImport } from './routes/continuity_.join.$token'
import { Route as ContinuityBoothDomainRouteImport } from './routes/continuity_.booth.$domain'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ShineRoute = ShineRouteImport.update({
  id: '/shine',
  path: '/shine',
  getParentRoute: () => rootRouteImport,
} as any)
const McflamingoRoute = McflamingoRouteImport.update({
  id: '/mcflamingo',
  path: '/mcflamingo',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorsRoute = DoorsRouteImport.update({
  id: '/doors',
  path: '/doors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinuityRoute = ContinuityRouteImport.update({
  id: '/continuity',
  path: '/continuity',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardRoute = BillboardRouteImport.update({
  id: '/billboard',
  path: '/billboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinuityJoinTokenRoute = ContinuityJoinTokenRouteImport.update({
  id: '/continuity_/join/$token',
  path: '/continuity/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinuityBoothDomainRoute = ContinuityBoothDomainRouteImport.update({
  id: '/continuity_/booth/$domain',
  path: '/continuity/booth/$domain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/continuity': typeof ContinuityRoute
  '/doors': typeof DoorsRoute
  '/lab': typeof LabRoute
  '/mcflamingo': typeof McflamingoRoute
  '/shine': typeof ShineRoute
  '/wallet': typeof WalletRoute
  '/continuity/booth/$domain': typeof ContinuityBoothDomainRoute
  '/continuity/join/$token': typeof ContinuityJoinTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/continuity': typeof ContinuityRoute
  '/doors': typeof DoorsRoute
  '/lab': typeof LabRoute
  '/mcflamingo': typeof McflamingoRoute
  '/shine': typeof ShineRoute
  '/wallet': typeof WalletRoute
  '/continuity/booth/$domain': typeof ContinuityBoothDomainRoute
  '/continuity/join/$token': typeof ContinuityJoinTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/continuity': typeof ContinuityRoute
  '/doors': typeof DoorsRoute
  '/lab': typeof LabRoute
  '/mcflamingo': typeof McflamingoRoute
  '/shine': typeof ShineRoute
  '/wallet': typeof WalletRoute
  '/continuity_/booth/$domain': typeof ContinuityBoothDomainRoute
  '/continuity_/join/$token': typeof ContinuityJoinTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billboard'
    | '/continuity'
    | '/doors'
    | '/lab'
    | '/mcflamingo'
    | '/shine'
    | '/wallet'
    | '/continuity/booth/$domain'
    | '/continuity/join/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billboard'
    | '/continuity'
    | '/doors'
    | '/lab'
    | '/mcflamingo'
    | '/shine'
    | '/wallet'
    | '/continuity/booth/$domain'
    | '/continuity/join/$token'
  id:
    | '__root__'
    | '/'
    | '/billboard'
    | '/continuity'
    | '/doors'
    | '/lab'
    | '/mcflamingo'
    | '/shine'
    | '/wallet'
    | '/continuity_/booth/$domain'
    | '/continuity_/join/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillboardRoute: typeof BillboardRoute
  ContinuityRoute: typeof ContinuityRoute
  DoorsRoute: typeof DoorsRoute
  LabRoute: typeof LabRoute
  McflamingoRoute: typeof McflamingoRoute
  ShineRoute: typeof ShineRoute
  WalletRoute: typeof WalletRoute
  ContinuityBoothDomainRoute: typeof ContinuityBoothDomainRoute
  ContinuityJoinTokenRoute: typeof ContinuityJoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shine': {
      id: '/shine'
      path: '/shine'
      fullPath: '/shine'
      preLoaderRoute: typeof ShineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcflamingo': {
      id: '/mcflamingo'
      path: '/mcflamingo'
      fullPath: '/mcflamingo'
      preLoaderRoute: typeof McflamingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doors': {
      id: '/doors'
      path: '/doors'
      fullPath: '/doors'
      preLoaderRoute: typeof DoorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continuity': {
      id: '/continuity'
      path: '/continuity'
      fullPath: '/continuity'
      preLoaderRoute: typeof ContinuityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboard': {
      id: '/billboard'
      path: '/billboard'
      fullPath: '/billboard'
      preLoaderRoute: typeof BillboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continuity_/join/$token': {
      id: '/continuity_/join/$token'
      path: '/continuity/join/$token'
      fullPath: '/continuity/join/$token'
      preLoaderRoute: typeof ContinuityJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continuity_/booth/$domain': {
      id: '/continuity_/booth/$domain'
      path: '/continuity/booth/$domain'
      fullPath: '/continuity/booth/$domain'
      preLoaderRoute: typeof ContinuityBoothDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillboardRoute: BillboardRoute,
  ContinuityRoute: ContinuityRoute,
  DoorsRoute: DoorsRoute,
  LabRoute: LabRoute,
  McflamingoRoute: McflamingoRoute,
  ShineRoute: ShineRoute,
  WalletRoute: WalletRoute,
  ContinuityBoothDomainRoute: ContinuityBoothDomainRoute,
  ContinuityJoinTokenRoute: ContinuityJoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
